import Head from 'next/head'
import GooglePayButton from '@google-pay/button-react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Pay Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="bg-sky-500/20 w-screen h-screen flex justify-center items-center">
        <div
          class="w-11/12 md:w-6/12 lg:w-4/12 h-1/4 flex justify-center items-center bg-white rounded-2xl shadow-2xl transition-all duration-500"
        ><GooglePayButton
            environment="TEST"
            paymentRequest={{
              apiVersion: 2,
              apiVersionMinor: 0,
              allowedPaymentMethods: [
                {
                  type: 'CARD',
                  parameters: {
                    allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
                    allowedCardNetworks: ['MASTERCARD', 'VISA'],
                  },
                  tokenizationSpecification: {
                    type: 'PAYMENT_GATEWAY',
                    parameters: {
                      gateway: 'checkoutltd',
                      gatewayMerchantId: process.env.NEXT_PUBLIC_CHECKOUT_MERCHANT_ID,
                    },
                  },
                },
              ],
              merchantInfo: {
                merchantId: '12345678901234567890',
                merchantName: 'Demo Merchant',
              },
              transactionInfo: {
                totalPriceStatus: 'FINAL',
                totalPriceLabel: 'Total',
                totalPrice: '100.00',
                currencyCode: 'USD',
                countryCode: 'US',
              },
            }}
            onLoadPaymentData={paymentRequest => {
              console.log('load payment data', JSON.parse(paymentRequest.paymentMethodData.tokenizationData.token));
            }}
          />
        </div>
      </div>
    </div>
  )
}
